//
//  WriterPerformance.m
//  Writer
//
//  Created by Hendrik Noeller on 03.04.16.
//  Copyright © 2016 Hendrik Noeller. All rights reserved.
//

#import <XCTest/XCTest.h>

#import "ContinousFountainParser.h"
#import "FastFountainParser.h"
#import "FountainParser.h"

@interface WriterPerformance : XCTestCase

@end

@implementation WriterPerformance

- (void)setUp {
    [super setUp];
    // Put setup code here. This method is called before the invocation of each test method in the class.
}

- (void)tearDown {
    // Put teardown code here. This method is called after the invocation of each test method in the class.
    [super tearDown];
}

- (void)testOwnPerformance {
    [self measureBlock:^{
        (void) [[ContinousFountainParser alloc] initWithString:longScript];
    }];
}

- (void)testFountainFastPerformance {
    [self measureBlock:^{
        (void) [[FastFountainParser alloc] initWithString:longScript];
    }];
}


- (void)testFountainPerformance {
    [self measureBlock:^{
        [FountainParser parseTitlePageOfString:longScript];
        [FountainParser parseBodyOfString:longScript];
    }];
}

- (void)testRemovePerformance {
    ContinousFountainParser *parser = [[ContinousFountainParser alloc] initWithString:longScript];
    [self measureBlock:^{
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
        [parser parseChangeInRange:NSMakeRange(3, 2) withString:@""];
    }];
}

- (void)testInsertPerformance {
    ContinousFountainParser *parser = [[ContinousFountainParser alloc] initWithString:longScript];
    [self measureBlock:^{
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
        [parser parseChangeInRange:NSMakeRange(30, 0) withString:@"ba"];
    }];
}


NSString* shortScript = @""
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n";


NSString* longScript = @""
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"He indeed looks very happy\n"
@"fade to:\n"
@".thisisaheading\n"
@"!THISISACTION\n"
@"~lyrics and stuff in this line\n"
@">transition\n"
@"      \n"
@"title: this is not the title page!\n"
@">center!<\n"
@"===\n"
@"======\n"
@"This is on a new page\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is on a new page\n"
@"Title: Script\n"
@"Author: Florian Maier\n"
@"Credit: Thomas Maier\n"
@"source: somewhere\n"
@"DrAft Date: 42.23.23\n"
@"Contact: florian@maier.de\n"
@"\n"
@"INT. DAY - LIVING ROOM\n"
@"EXT. DAY - LIVING ROOM\n"
@"Peter sits somewhere and does something\n"
@"\n"
@"PETER\n"
@"I Like sitting here\n"
@"it makes me happy\n"
@"\n"
@"CHRIS ^\n"
@"i'm also a person!\n"
@"\n"
@"HARRAY\n"
@"(slightly irritated)\n"
@"Why do i have parentheses?\n"
@"They are weird!\n"
@"\n"
@"CHIRS ^\n"
@"(looking at harray)\n"
@"Why am i over here?\n"
@"  \n"
@"And I have holes in my text!\n"
@"\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
@"This is useless action to blow stuff uppppp\n"
;

@end
